### ISSUE TITLE
关于targetDir的问题

### ISSUE THREAD

**Issue by FengZeming** [cyyjs/scss2css-vscode#2]
设置 ：  "Scss2Css.targetDir": "../css"
我的项目目录是有h5_test的
![image](https://user-images.githubusercontent.com/12960884/30731809-2eb2f7f6-9fa2-11e7-8bc0-487b2b1c8dc9.png)
但实际上却是这样
![image](https://user-images.githubusercontent.com/12960884/30731819-37686340-9fa2-11e7-9ce0-fdb3a96b3222.png)

我需要的是：
c:\Users\Administrator\Desktop\tes\h5_test\css\style.css

请问这种情况我怎么设置呢？

**Comment by cyyjs** [comment]
相对路径设置是基于项目在vscode中的根目录的
例如：
![image](https://user-images.githubusercontent.com/2883079/30770476-7f6d176c-9ff7-11e7-8065-9a6150b558d6.png)
根目录为`a`, 所以可以设置为`"Scss2Css.targetDir": "./a/css"`

如果你的项目根目录为`h5_test` ，设置为`"./h5_test/css"` 即可

另外也可以设置绝对路径
```
"Scss2Css.targetDir": "c:\Users\Administrator\Desktop\tes\h5_test\css"
```
