### ISSUE TITLE
Internal Error: File to read not found or unreadable: /sass/main.scss

### ISSUE THREAD

**Issue by xianghongai** [cyyjs/scss2css-vscode#4]
Internal Error: File to read not found or unreadable: /sass/main.scss

![default](https://user-images.githubusercontent.com/2075006/34093099-6cbe4e1c-e401-11e7-9cbb-0825bee48b2d.png)

**Comment by cyyjs** [comment]
检查你的scss文件是否拥有读取权限？

**Comment by xianghongai** [comment]
:joy: 我还特意管理员权限运行了编辑器，还是不行，算了，THX。:grinning:
