### ISSUE TITLE
Internal Error: File to read not found or unreadable: /sass/main.scss

### ISSUE THREAD

**Issue by qq89987112** [cyyjs/scss2css-vscode#6]

**Comment by cyyjs** [comment]
保存`scss`文件，会自动编译当前目录下的`main.scss`文件，没有此文件就会报类似的错误，可以通过修改配置项设置主文件：

在`vscode`设置中找到`Scss2Css配置`，修改`Scss2Css.mainFile`配置项即可。

**Comment by oxsd** [comment]
What is the status of this issue?  I'm experiencing it, too, and have not not found the fix.
