### ISSUE TITLE
关于配置的一些建议

### ISSUE THREAD

**Issue by bin-dogami** [cyyjs/scss2css-vscode#7]
1、文档描述不太详尽，Scss2Css.formats 配置应该需要更详情说明吧？
2、编译后生成了两个文件，能否让我自主控制是生成非压缩文件或者压缩文件，同时文件名可自定义？

**Comment by cyyjs** [comment]
@old-bin 已经更新相关[配置项文档](https://cyyjs.github.io/scss2css-vscode/)
